name: Dispatch ruyi-package-ci

on:
  push:
    tags:
      - '*'

jobs:
  dispatch-ruyi-package-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch ruyi-package-ci
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.PAT_RUYI_PACKAGE_CI }}
          repo: ruyisdk/ruyi-package-ci
          ref: master
          workflow: deb.yml
          inputs: '{"ruyi_deb_ref": "${{ github.ref_name }}"}'
