name: Dispatch ruyi-package-ci

on:
  push:
    tags:
      - '*'

jobs:
  dispatch-ruyi-package-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit
      - name: Dispatch ruyi-package-ci
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.GHA_PAT_RUYI_PACKAGE_CI_RW }}
          repo: ruyisdk/ruyi-package-ci
          ref: master
          workflow: deb.yml
          inputs: '{"ruyi_deb_ref": "${{ github.ref_name }}"}'
